export const photos = [
  { src: "img1.png", height: 2, width: 2 },
  { src: "img2.png", height: 2, width: 2 },
  { src: "img3.png", height: 2, width: 2 },
  { src: "img4.png", height: 2, width: 2 },
  { src: "img5.png", height: 2, width: 2 },
  { src: "img6.png", height: 2, width: 2 },
  { src: "img7.png", height: 2, width: 2 },
  { src: "img8.jpeg", height: 2, width: 2 },
  { src: "img9.jpeg", height: 2, width: 2 },
  { src: "img10.jpeg", height: 2, width: 2 },
  { src: "img11.jpeg", height: 2, width: 2 },
  { src: "img12.jpeg", height: 2, width: 2 },
  { src: "img13.jpeg", height: 2, width: 2 },
  { src: "img14.jpeg", height: 2, width: 2 },
  { src: "img15.jpeg", height: 2, width: 2 },
  { src: "img16.jpeg", height: 2, width: 2 },
  { src: "img17.jpeg", height: 2, width: 2 },
  { src: "img18.jpeg", height: 2, width: 2 },
  { src: "img19.jpeg", height: 2, width: 2 },
  { src: "img20.jpeg", height: 2, width: 2 },
  { src: "img21.jpeg", height: 2, width: 2 },
  { src: "img22.jpeg", height: 2, width: 2 },
  { src: "img23.jpeg", height: 2, width: 2 },
];
