export const photos = [
  { src: "img1.png", height: 2, width: 2 },
  { src: "img2.png", height: 2, width: 2 },
  { src: "img3.png", height: 2, width: 2 },
  { src: "img4.png", height: 2, width: 2 },
  { src: "img5.png", height: 2, width: 2 },
  { src: "img6.png", height: 2, width: 2 },
  { src: "img7.png", height: 2, width: 2 },
  { src: "img7.png", height: 2, width: 2 },
  { src: "img7.png", height: 2, width: 2 },
  { src: "img7.png", height: 2, width: 2 },
  { src: "img7.png", height: 2, width: 2 },
  { src: "img7.png", height: 2, width: 2 },
  { src: "img7.png", height: 2, width: 2 },
];
